### ISSUE TITLE
Repeated name of college show up in Join Class

### ISSUE THREAD

**Issue by gerryzqx** [CSC59939/Rails#66] opened 2018-11-15 00:50 UTC
The same name of college appears in the search list join class.
![screen shot 2018-11-14 at 7 48 50 pm](https://user-images.githubusercontent.com/14956377/48522374-65ea2a80-e846-11e8-8f7b-574fbb671d6f.jpg)

**Comment by ayushyamitabh** [comment] 2018-11-17 02:59
@gerryzqx thank you for bringing this to our attention, seems to be a duplicate of #70 we'll be tracking the progress for this bug on that issue - please look to that issue to check for any progress on this bug.

**Closed by ayushyamitabh** 2018-11-17 02:59 UTC
