### ISSUE TITLE
A lot of Columbia Colleges

### ISSUE THREAD

**Issue by buenoluis007** [CSC59939/Rails#61] opened 2018-11-15 00:46 UTC
Whenever I type to join Columbia College, what should I choose?!?!

![image](https://user-images.githubusercontent.com/33500965/48522233-dfcde400-e845-11e8-8786-558dd92c4b98.png)

**Comment by ayushyamitabh** [comment] 2018-11-17 03:09
@buenoluis007 thank you for bringing this to our attention, seems to be a duplicate of #70 we'll be tracking the progress for this bug on that issue - please look to that issue to check for any progress on this bug.

closing this issue.

**Closed by ayushyamitabh** 2018-11-17 03:09 UTC

**Comment by edwin0108** [comment] 2018-12-05 07:16
Resolved in #73 
Closing.
