### ISSUE TITLE
blank screen.

### ISSUE THREAD

**Issue by fspringer** [CSC59939/Rails#63] opened 2018-11-15 00:47 UTC
when trying to access the main webpage, i got a blank screen.

**Comment by ayushyamitabh** [comment] 2018-11-17 03:06
@fspringer we were unable to reproduce this error, should you come by this error again please let us know further details and we will look into it again.

This might have occurred due to our Firebase quota limitations, and unexpectedly high traffic during the night of testing.

closing for now

**Closed by ayushyamitabh** 2018-11-17 03:06 UTC
